[tool.poetry]
name = "flockwave-async"
version = "1.1.0"
description = "Asynchronous utility functions, mostly for Trio"
authors = ["Tamas Nepusz <tamas@collmot.com>"]
packages = [
    { include = "flockwave", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
trio = ">=0.18.0"
trio-util = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-trio = "^0.6.0"
pytest-cov = "^3.0.0"
coverage = {extras = ["toml"], version = "^6.0"}

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
